POST http://localhost:8020/api
Content-Type: application/json
X-API-Key: abc

{
    "url": "https://intervest.io/blackrock-dan-investor-besar-lainnya-perkuat-posisi-untr-bersinar-tahun-2024"
}

### GET ALL

GET http://localhost:8020/api/a?page=1
Content-Type: application/json
X-API-Key: abc


### DELETE BY ID

DELETE http://localhost:8020/api/a/f74f9
Content-Type: application/json
X-API-Key: abc


### GET BY ID

GET http://localhost:8020/api/a/613f5
Content-Type: application/json
X-API-Key: abc